import {
  Upload,
  ScanSearch,
  BadgeCheck,
  Activity,
  FolderOpen,
  Pencil,
  RefreshCw,
  Bookmark,
  TrendingUp,
  ShieldCheck,
  Database,
  Fingerprint,
  MessageSquare,
  FileText,
  Target,
  Award,
  type LucideIcon,
} from "@/components/ui/icons";
import type { TimelineEventType } from "@/types/provenance";

export const EVENT_ICON: Record<TimelineEventType, LucideIcon> = {
  FIRST_UPLOAD: Upload,
  IMAGE_REANALYSIS: ScanSearch,
  CONDITION_UPDATED: BadgeCheck,
  CONFIDENCE_CHANGED: Activity,
  COLLECTION_ADDED: FolderOpen,
  COLLECTION_UPDATED: Pencil,
  OWNERSHIP_CHANGED: RefreshCw,
  WISHLIST_ADDED: Bookmark,
  WISHLIST_REMOVED: Bookmark,
  MARKET_VALUE_UPDATED: TrendingUp,
  AUTHENTICATION_UPDATED: ShieldCheck,
  MEMORY_IMPACT: Database,
  DNA_IMPACT: Fingerprint,
  CONVERSATION_REFERENCED: MessageSquare,
  LEGACY_REPORT_GENERATED: FileText,
  GOAL_CONTRIBUTION: Target,
  ACHIEVEMENT_CONTRIBUTION: Award,
  MANUAL_NOTE: Pencil,
};
